package tokens;

public enum KeywordType { ASSERT, BOOLEAN, BREAK, CASE, CATCH, CHAR,
	CLASS, CONTINUE, DEFAULT, DO, DOUBLE, ELSE, ENUM, EXTENDS,
	FINAL, FINALLY, FLOAT, FOR, IF, IMPLEMENTS, IMPORT,
	INSTANCEOF, INT, INTERFACE, LONG, NATIVE, NEW, PACKAGE,
	PRIVATE, PROTECTED, PUBLIC, RETURN, SHORT, STATIC,
	STRICTFP, SUPER, SWITCH, SYNCHRONIZED, THIS, THROW, THROWS,
	TRANSIENT, TRY, VOID, VOLATILE, WHILE, FALSE, NULL, TRUE
};
